//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaTelefonica.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cliente
    {
        [Required(ErrorMessage = "Por favor informe um id.", AllowEmptyStrings = false)]
        [Display(Name = "Id")]
        public int id_cliente { get; set; }
        [Required(ErrorMessage ="Por favor informe um nome.", AllowEmptyStrings = false)]
        [Display(Name = "Nome")]
        public string nm_cliente { get; set; }
        [Required(ErrorMessage = "Por favor informe um telefone.", AllowEmptyStrings = false)]
        [Display(Name = "Telefone")]
        public Nullable<int> ds_telefone { get; set; }
    }
}
